name: Android Build

on:
  push:
    branches:
      - master-android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34  # Target SDK and Compile SDK level
          build-tools: 34.0.0  # Corresponding build tools version

      - name: Set up environment variable
        env:
          VISION_API_KEY: ${{ secrets.VISION_API_KEY }}
          VISION_API_ENDPOINT: ${{ secrets.VISION_API_ENDPOINT }}
        run: |
          touch ./app/secrets.properties
          ls -l ./app/
          echo "VISION_API_KEY=${VISION_API_KEY}" >> ./app/secrets.properties
          echo "VISION_API_ENDPOINT=${VISION_API_ENDPOINT}" >> ./app/secrets.properties

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/kotlin
            ~/.gradle/daemon
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Bump version number
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign Release AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}' >    service_account.json

#      - name: Publish to Play Store BETA
#        id: publish
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: service_account.json
#          packageName: com.originb.inkwisenote
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: beta